#!/bin/bash
# Configuration d'un serveur Public-Cloud
#
# Install base
echo "Install Base"
yum install epel-release -y
yum install -y net-tools
# Update Centos
echo "Update"
yum update -y
yum install wget -y
yum install nano -y
# Configuration IP Eth0:0
echo "IP Settings Eth0:0"
touch /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'DEVICE=eth0:0' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'BOOTPROTO=static' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'IPADDR=XX.XXX.XXX.XX' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'NETMASK=255.255.255.255' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'BROADCAST=XX.XXX.XXX.XX' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
echo 'ZONE=public' >> /etc/sysconfig/network-scripts/ifcfg-eth0:0
ifup eth0:0
# Configuration IP VRack
echo "IP Settings VRack"
touch /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'DEVICE=eth1' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'BOOTPROTO=static' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'IPADDR=192.168.0.102' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'NETWORK=192.168.0.0' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'NETMASK=255.255.0.0' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'ONBOOT=yes' >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo 'ZONE=internal' >> /etc/sysconfig/network-scripts/ifcfg-eth1
ifup eth1
# Configuration FirewallD
echo "Conf FirewallD"
systemctl start firewalld.service
firewall-cmd --set-default-zone=public
systemctl restart firewalld.service
systemctl enable firewalld.service
# FirewallD DNS Serveur
firewall-cmd --zone=public --permanent --add-icmp-block=echo-request
firewall-cmd --zone=public --permanent --add-service=dns
firewall-cmd --zone=public --permanent --add-service=https
firewall-cmd --zone=public --permanent --add-service=ntp
firewall-cmd --zone=public --permanent --add-service=dhcpv6-client
firewall-cmd --zone=public --permanent --remove-service=ssh
firewall-cmd --zone=internal --permanent --add-service=ssh
# Configuration Hostname
echo "Hostname settings"
sed -i '1 i\preserve_hostname: true' /etc/cloud/cloud.cfg
sed -i '1 i\manage_etc_hosts: false: true' /etc/cloud/cloud.cfg
rm -rf /etc/hostname
touch /etc/hostname
echo 'docker.kameleon.studio' >> /etc/hostname
rm -rf /etc/hosts
touch /etc/hosts
echo '127.0.0.1 XXXX.yourdomain.name XXXX' >> /etc/hosts
echo '127.0.0.1 localhost' >> /etc/hosts
echo '::1 XXXX.yourdomain.name XXXX' >> /etc/hosts
echo '::1 localhost' >> /etc/hosts
# End of Script
echo "End of Script"
reboot
exit
